version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: prediction
      POSTGRES_PASSWORD: prediction
      POSTGRES_DB: prediction
    ports:
      - '5432:5432'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
