# Generated by Django 4.2.16 on 2024-10-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='name',
            new_name='title',
        ),
    ]
