# Generated by Django 4.2.16 on 2024-10-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0002_rename_name_app_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'okay'), ('4', 'good'), ('5', 'excellent')])),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mart.app')),
            ],
        ),
    ]
