# Generated by Django 4.2.16 on 2024-10-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0003_apprating'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprating',
            name='opinion',
            field=models.TextField(default='no opinion'),
        ),
        migrations.AlterField(
            model_name='apprating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 'very bad'), (2, 'bad'), (3, 'okay'), (4, 'good'), (5, 'excellent')]),
        ),
    ]
