# Generated by Django 4.2.16 on 2024-10-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0008_alter_cartproduct_cart_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
