# Generated by Django 4.2.16 on 2024-10-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0009_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
