# Generated by Django 4.2.16 on 2024-10-07 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mart', '0010_remove_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('percent', models.IntegerField(choices=[(0, '0'), (5, '5%'), (15, '15%'), (25, '25%'), (50, '50%')], default=0, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mart.app')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mart.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
