# Generated by Django 4.2.16 on 2024-10-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0011_discount_discountuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(choices=[(0, '0'), (5, '5%'), (15, '15%'), (25, '25%'), (50, '50%')], default=0),
        ),
    ]
